#!/usr/bin/env bash
# scripts/repro-crash.sh — Reproduce a saved AFL crash input standalone.
#
# After a fuzzing session produces saved_crashes > 0, AFL saves the
# minimized input under <out>/default/crashes/id:N,sig:06,... This
# script reads that file, runs the standalone fuzzer harness against
# it, and pulls the ASAN report out of the launcher-managed
# $ASAN_LOG_DIR/crash.<pid>.
#
# Pre-fix status (commit 82caede): this script would silently miss
# the bug because resolve_bytes() hashed the *filename string* as
# the PRNG seed instead of reading the file's 46-byte body. The fix
# makes resolve_bytes() try the cwd-prefixed file path, so
# relative paths work the same as absolute ones.
#
# Usage:
#   scripts/repro-crash.sh <crash-file>
#   scripts/repro-crash.sh afl-findings-bytes/default/crashes/id:000000,sig:06,...
#   scripts/repro-crash.sh afl-findings-bytes/default/crashes/id:*      # first match
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

crash_file="${1:-}"
if [[ -z "$crash_file" ]]; then
  echo "usage: $0 <crash-file>" >&2
  echo "  crash-file: full path or relative; wildcards expand to first match" >&2
  exit 2
fi

# Expand a glob to first match.
if [[ "$crash_file" == *"*"* ]]; then
  IFS= read -r -d '' crash_file < <(
    compgen -G "$crash_file" 2>/dev/null | head -n1 | tr '\n' '\0' \
      || true
  )
  if [[ -z "${crash_file:-}" ]]; then
    echo "no crash file matched glob: $1" >&2
    exit 2
  fi
fi
if [[ ! -f "$crash_file" ]]; then
  echo "not a file: $crash_file" >&2
  exit 2
fi

mkdir -p afl-asan-logs
echo "repro: $crash_file ($(wc -c < "$crash_file") bytes)"
echo

# Run the standalone harness with the launcher that writes ASAN
# reports to afl-asan-logs/repro.<pid>. The harness still uses
# fuzz-crashhunter.lua directly (no repro.lua emission), so this is
# the path for re-running the saved bytes through the original fuzzer
# PRNG. We do NOT use scripts/_lib-asan.sh here because that helper
# runs an arbitrary repro.lua; we need the launcher-managed ASAN
# log file at a specific path that fuzz-crashhunter.sh's launcher
# writes to.
ASAN_OPTIONS="detect_leaks=0:abort_on_error=1:symbolize=1:halt_on_error=1:allocator_may_return_null=1:log_path=$ROOT/afl-asan-logs/repro" \
  timeout 60 env FUZZ_QUIET=1 VIMRUNTIME="$ROOT/deps/neovim/runtime" \
    "$ROOT/deps/neovim/build-afl/bin/nvim" --headless --clean -i NONE -n \
      -l "$ROOT/fuzz-crashhunter.lua" "$crash_file" 80 \
      2>/dev/null | head -3
rc=$?

echo
echo "rc=$rc  (134 = SIGABRT, 0 = clean exit, 1 = ASAN abort, etc.)"

# The launcher writes ASAN reports to afl-asan-logs/crash.<pid>. Find
# the most recent non-empty file matching that prefix generated by
# this run.
log=$(find afl-asan-logs -name 'crash.*' -newer "$crash_file" \
       -size +0 2>/dev/null | head -1)
if [[ -n "$log" ]]; then
  echo
  echo "ASAN report ($log):"
  head -25 "$log"
fi